const employees = [
  {
    id: 1,
    name: "Rajesh Sharma",
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        title: "Complete project report",
        description: "Finish the final report for the client presentation.",
        date: "2024-10-15",
        category: "Work",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Team meeting preparation",
        description: "Prepare slides for the upcoming team meeting.",
        date: "2024-10-16",
        category: "Work",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Update CRM system",
        description: "Add new clients to the CRM system.",
        date: "2024-10-17",
        category: "Work",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 2,
    name: "Anjali Verma",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "Database maintenance",
        description: "Optimize database performance and remove obsolete data.",
        date: "2024-10-10",
        category: "Work",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Client feedback review",
        description: "Analyze feedback and create a summary report.",
        date: "2024-10-18",
        category: "Work",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Documentation update",
        description: "Update technical documentation for internal processes.",
        date: "2024-10-19",
        category: "Work",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 0,
      failed: 1,
    },
  },
  {
    id: 3,
    name: "Priya Iyer",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Create marketing plan",
        description: "Draft a marketing strategy for the new product.",
        date: "2024-10-12",
        category: "Marketing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Website redesign review",
        description: "Evaluate design proposals for the company website.",
        date: "2024-10-13",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Social media campaign",
        description: "Launch a social media campaign for product promotion.",
        date: "2024-10-20",
        category: "Marketing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Product packaging design",
        description: "Collaborate with the design team for new packaging.",
        date: "2024-10-21",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
    taskCount: {
      active: 3,
      newTask: 2,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 4,
    name: "Vikram Mehta",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "Budget planning",
        description: "Prepare the budget for the next quarter.",
        date: "2024-10-11",
        category: "Finance",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Supplier negotiation",
        description: "Negotiate new contracts with suppliers.",
        date: "2024-10-18",
        category: "Operations",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Inventory check",
        description: "Perform a check on current stock levels.",
        date: "2024-10-19",
        category: "Operations",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 5,
    name: "Sunita Patel",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "Customer support training",
        description: "Train new customer support representatives.",
        date: "2024-10-14",
        category: "Training",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Onboarding new employees",
        description: "Oversee the onboarding process for new hires.",
        date: "2024-10-16",
        category: "HR",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Performance reviews",
        description: "Conduct performance reviews for team members.",
        date: "2024-10-20",
        category: "HR",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Policy update review",
        description: "Review updates to company policies.",
        date: "2024-10-21",
        category: "HR",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
    taskCount: {
      active: 4,
      newTask: 2,
      completed: 1,
      failed: 0,
    },
  },
];

const admin = [
  {
    id: 1,
    name: "Amitabh Gupta",
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employee = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employee, admin };
};
